### ISSUE TITLE
detect @ mentions and # projects

### ISSUE THREAD

**Issue by grimreaper** [PageUpPeopleOrg/arcanist-patches#1]
it would be nice to highlight @ mentions and # projects along with other monograms specially.

**Comment by hach-que** [comment]
What is this in regard to?

Since Arcanist is purely a command-line program, and any user input is driven through an external editor, I'm not sure what behaviour you're asking for.

In addition, this repository is a list of patches that we apply to upstream Arcanist.  Unless this is an issue with regards specifically to the patches we apply (the only one we have at the moment prevents "arc diff" from continuing if pushing to staging fails), it should probably be filed upstream.

**Comment by grimreaper** [comment]
wrong repo - sorry. I thought I was commenting on a vim-arcanist repo :/
